version: "3.8"

networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - dev